library(tidyverse)
library(gganimate)
library(gapminder)
library(gifski)
theme_set(theme_classic())
games <- read.csv("data/vgsales.csv")


# tidy data
games$Year <- as.numeric(as.character(games$Year))

games <- games %>% 
  dplyr::filter(!is.na(Year))


# create all time data as of each year
games_new <- games %>% 
         dplyr::filter(Year == min(games$Year)) %>% 
         dplyr::mutate(Year_Group = 1980)

for (i in 1981:2016) {
  games_new <- games %>% 
    dplyr::filter(Year <= i) %>% 
    dplyr::mutate(Year_Group = i) %>% 
    dplyr::bind_rows(games_new)
}

# generate top n ranking by year group

anim_games <- games_new %>%
  mutate(Year_Group = as.numeric(as.character(Year_Group))) %>% 
  group_by(Year_Group) %>%
  # The * 1 makes it possible to have non-integer ranks while sliding
  mutate(rank = min_rank(-Global_Sales) * 1,
         Value_rel = Global_Sales/Global_Sales[rank==1],
         Value_lbl = paste0(" ",Global_Sales)) %>%
  filter(rank <= 25) %>%
  ungroup()

# create animated barchart

p <- ggplot(anim_games, aes(rank, group = Platform, 
                     fill = as.factor(Platform), color = as.factor(Platform))) +
  geom_tile(aes(y = Global_Sales/2,
                height = Global_Sales,
                width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(Name, " ")), vjust = 0.2, hjust = 1) +
  geom_text(aes(y = Global_Sales, label = Value_lbl, hjust=0)) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  labs(title='{closest_state}', x = "", y = "Global Sales in millions",
       caption = "Sources: Kaggle Dataset | Plot generated by @dr_keithmcnulty") +
  theme(plot.title = element_text(hjust = 0, size = 22),
        axis.ticks.y = element_blank(),  
        axis.text.y  = element_blank(),  
        plot.margin = margin(1,2,1,8, "cm")) +
  transition_states(Year_Group, transition_length = 4, state_length = 1) +
  ease_aes('cubic-in-out')

# save as preferred rendered format

animate(p, 200, fps = 5, duration = 150, width = 1000, height = 600, renderer = ffmpeg_renderer("anim.mp4"))
